name: 'retail_dw'
version: '1.0.0'
config-version: 2

profile: 'retail_dw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail_dw:
    staging:
      +materialized: table
      +schema: staging
    dimension:
      +materialized: table
      +schema: dimension
    fact:
      +materialized: table
      +schema: fact
    mart:
      +materialized: table
      +schema: mart
