retail_dw:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: trino
      host: trino
      port: 8080
      database: mysql
      schema: retail_db
      threads: 4
      http_scheme: http
